function u = impedance_controller(x,xd,Fa,Y,Yd,Ydd)
%IMPEDANCE_CONTROLLER
%    U = IMPEDANCE_CONTROLLER(X,XD,FA,Y,YD,YDD)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Nov-2016 10:33:39

u = Fa.*(-1.0./7.0)+Y.*2.571428571428571e2+Yd.*(6.0e1./7.0)+Ydd.*3.0-x.*2.571428571428571e2-xd.*(4.6e1./7.0);
