function u_func = u_func(in1,in2,in3,in4)
%U_FUNC
%    U_FUNC = U_FUNC(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Dec-2016 10:35:49

fa1 = in4(1,:);
fa2 = in4(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
q1d = in2(1,:);
q2d = in2(2,:);
q1dd = in3(1,:);
q2dd = in3(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(q1);
t5 = sin(q2);
t6 = cos(q2);
t7 = q2dd.*(4.03e2./2.4e2);
t8 = t3.*(9.81e2./4.0e1);
t9 = sin(t2);
t10 = fa1.*t9;
u_func = [q1d.*1.0e1+q1dd.*1.669166666666667e1-t4.*1.103625e2+t7+t8+t10-fa2.*t3+fa2.*t4.*(3.0./2.0)+q1dd.*t5.*(1.5e1./2.0)+q2dd.*t5.*(1.5e1./4.0)+fa1.*cos(q1).*(3.0./2.0)+q2d.^2.*t6.*(1.5e1./4.0)+q1d.*q2d.*t6.*(1.5e1./2.0);q2d.*1.0e1+q1dd.*(4.03e2./2.4e2)+t7+t8+t10-fa2.*t3+q1dd.*t5.*(1.5e1./4.0)-q1d.^2.*t6.*(1.5e1./4.0)];
